require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ServiceTypesController do

  # This should return the minimal set of attributes required to create a valid
  # ServiceType. As you add validations to ServiceType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ServiceTypesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all service_types as @service_types" do
      service_type = ServiceType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:service_types).should eq([service_type])
    end
  end

  describe "GET show" do
    it "assigns the requested service_type as @service_type" do
      service_type = ServiceType.create! valid_attributes
      get :show, {:id => service_type.to_param}, valid_session
      assigns(:service_type).should eq(service_type)
    end
  end

  describe "GET new" do
    it "assigns a new service_type as @service_type" do
      get :new, {}, valid_session
      assigns(:service_type).should be_a_new(ServiceType)
    end
  end

  describe "GET edit" do
    it "assigns the requested service_type as @service_type" do
      service_type = ServiceType.create! valid_attributes
      get :edit, {:id => service_type.to_param}, valid_session
      assigns(:service_type).should eq(service_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ServiceType" do
        expect {
          post :create, {:service_type => valid_attributes}, valid_session
        }.to change(ServiceType, :count).by(1)
      end

      it "assigns a newly created service_type as @service_type" do
        post :create, {:service_type => valid_attributes}, valid_session
        assigns(:service_type).should be_a(ServiceType)
        assigns(:service_type).should be_persisted
      end

      it "redirects to the created service_type" do
        post :create, {:service_type => valid_attributes}, valid_session
        response.should redirect_to(ServiceType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved service_type as @service_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceType.any_instance.stub(:save).and_return(false)
        post :create, {:service_type => {}}, valid_session
        assigns(:service_type).should be_a_new(ServiceType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceType.any_instance.stub(:save).and_return(false)
        post :create, {:service_type => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested service_type" do
        service_type = ServiceType.create! valid_attributes
        # Assuming there are no other service_types in the database, this
        # specifies that the ServiceType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ServiceType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => service_type.to_param, :service_type => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested service_type as @service_type" do
        service_type = ServiceType.create! valid_attributes
        put :update, {:id => service_type.to_param, :service_type => valid_attributes}, valid_session
        assigns(:service_type).should eq(service_type)
      end

      it "redirects to the service_type" do
        service_type = ServiceType.create! valid_attributes
        put :update, {:id => service_type.to_param, :service_type => valid_attributes}, valid_session
        response.should redirect_to(service_type)
      end
    end

    describe "with invalid params" do
      it "assigns the service_type as @service_type" do
        service_type = ServiceType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceType.any_instance.stub(:save).and_return(false)
        put :update, {:id => service_type.to_param, :service_type => {}}, valid_session
        assigns(:service_type).should eq(service_type)
      end

      it "re-renders the 'edit' template" do
        service_type = ServiceType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceType.any_instance.stub(:save).and_return(false)
        put :update, {:id => service_type.to_param, :service_type => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested service_type" do
      service_type = ServiceType.create! valid_attributes
      expect {
        delete :destroy, {:id => service_type.to_param}, valid_session
      }.to change(ServiceType, :count).by(-1)
    end

    it "redirects to the service_types list" do
      service_type = ServiceType.create! valid_attributes
      delete :destroy, {:id => service_type.to_param}, valid_session
      response.should redirect_to(service_types_url)
    end
  end

end
